### ISSUE TITLE
Cannot read property 'width' of undefined $.().width()

### ISSUE THREAD

**Issue by aalimovs** [jerel/ember-cli-loading-slider#14]
Tried the addon on a fresh ember project, getting an error:

```
Uncaught TypeError: Cannot read property 'width' of undefined @ loading-slider.js:37
```

Same error at line 105 if `expanding=true`.

Am I missing something?

**Comment by jerel** [comment]
I think this might happen when the loading slider component is set to
expanding before the route's template is rendered. This should be
investigated and fixed, there's an open pull request related to it.

**Comment by aalimovs** [comment]
I had a look at the source, it seems to error because it tries to get width before didInsertElement() has done its job.

Moving `this.manage()` from `initialize()` to `didInsertElement()` fixed this. I'll do a PR later.

I'm not sure if there were any Ember changes that caused this, but I don't get how it's working for anyone else?

**Comment by juanesarango** [comment]
@aalimovs came here to report this same issue. I'm getting this error while making acceptance testing. Made the changes you propose locally while your fix is accepted and it works smoothly. 
Thanks man.
