### ISSUE TITLE
"Assertion Failed" error

### ISSUE THREAD

**Issue by cbetta** [jerel/ember-cli-loading-slider#17]
Ember: 2.2.0
Ember CLI: 1.13.13
Ember Data:  2.2.1

Error:
```
Uncaught Error: Assertion Failed: The controller named 'application' could not be found. Make sure that this route exists and has already been entered at least once. If you are accessing a controller not associated with a route, make sure the controller class is explicitly defined.
```

Seems to come from the mixin: https://github.com/jerel/ember-cli-loading-slider/blob/master/app/mixins/loading-slider.js#L6

**Comment by jerel** [comment]
The route mixin expects the controller to be explicitly defined. Based on the error message I suspect you don't have an `application` controller.

Alternatively if you don't want to use controllers in your app then skip the mixin and implement your own logic in the route that sets a value that you can bind to the `{{loading-slider isLoading=foo}}` attribute

**Comment by cbetta** [comment]
I actually did have an application controller. :/

**Comment by jerel** [comment]
Was there any further info found on this? I don't feel like I have enough context to fix anything so I'm closing for now. If there's something to be done yet just shout
