### ISSUE TITLE
This does not seem to work on Ember 2.4

### ISSUE THREAD

**Issue by devotox** [jerel/ember-cli-loading-slider#20]
I followed your instructions exactly and i see the Component added but the loading event never actually starts

**Comment by jerel** [comment]
@devotox as a workaround you can use a boolean property of your choosing on the component's `isLoading` attribute. Toggle it via an action, router event, etc.

**Comment by devotox** [comment]
The loading attribute does get set within the controller. Has the mixin runs and then the didTransition runs and sets it to false so all that works. Its just the actual loading animation never shows up

**Comment by leojpod** [comment]
Same here on 2.3

**Comment by jerel** [comment]
Please try v1.3.0, it now is implemented via a service which should work well with Ember v2.x and has the flexibility to do whatever you need. Please open an issue for any further trouble.
